### ISSUE TITLE
Подключение магазина

### ISSUE THREAD

**Issue by dani32iz** [rees46/rees46_cscart_embedded#11]
1. Удаление из корзины. У нас есть 4 способа удалить товар из корзины, я так и не понял какой сработал, потому что какой то не работал.
   а) Блок "Корзина"
   б) Крестик у каждого товара на странице "Корзина"
   в) Кнопка "Очистить корзину" на странице корзина
   г) Крестик у товаров в правой колонке на странице "Оформить заказ"
2. Что такое "Оценка" ?
3. Не смог обнаружить блоки: 

а) Посмотрите также
б) Сейчас покупают
1. Создал тестовый заказ, в списке заказов в личном кабинете rees46
   ID пользователя: 39856646
   Откуда этот ID, я покупал как авторизованный покупатель.

**Comment by noff** [comment]
> Откуда этот ID, я покупал как авторизованный покупатель.
> Это внутренний ID в REES46. Внешние ID пока не выводятся.

Оценка – вид отношения пользователя к товару после покупки. В плагинах к CMS не используется.

Блоки "Сейчас покупают" и "Посмотрите также" требуют активного поведения более одного пользователя. 
Для тестирования "С этим также покупают" необходимо купить два товара. Затем в режиме инкогнито (чтобы гарантировано была свежая сессия) открыть страницу одного из купленных товаров и увидеть в рекомендациях второй товар. Одному и тому же пользователю одни и те же товары не рекомендуются.

Для тестирования "Прямо сейчас покупают" необходимо оформить несколько заказов, затем в режиме инкогнито перейти на страницу, где выводится этот блок и увидеть недавно купленные другими пользователями товары. Пользователю не рекомендуется то, что он покупал.

По удалению из корзины: есть ли стандартны хук, вызывающийся для всех способов удаления товара из корзины, чтобы не вмешиваться в поведение фронтенда?
