### ISSUE TITLE
Правки шаблона блока

### ISSUE THREAD

**Issue by dani32iz** [rees46/rees46_cscart_embedded#6]
design/themes/basic/templates/addons/rees46/blocks/recommenders.tpl
1. Количество колонок лучше вынести в настройку блока.

```
   columns=4
```
1. Заголовок можно брать из $block , там должно быть название блока которое вводит клиент в настройка блока. Классы нужно использовать стандартные, как у других блоков.

```
   <h1>{$rees46_title}</h1>
```
1. Скрипты в новой версии вырезаются и переносятся в подвал, если это не нужно, то добавить атрибут data-no-defer
2. Что будет если клиент добавит несколько блоков на страницу.

```
    <script>
        if( REES46 && REES46.showPromotion ) {
            $('.reed46-promo').html(REES46.getPromotionBlock());
        }
    </script>
```

**Comment by PNixx** [comment]
1. done
2. При ajax рендеринге переменной $block уже не существует и не возможно достать данные о блоке, вся информация передается только в app/addons/rees46/controllers/frontend/rees46.php
3. Это ни как не повлияет
4. done
