### ISSUE TITLE
Выгрузка заказов: Notice

### ISSUE THREAD

**Issue by dani32iz** [rees46/rees46_cscart_embedded#9]
PHP Notice

Message

unserialize(): Error at offset 8 of 11 bytes
Error at

app/functions/fn.cart.php, line: 1905
Backtrace

File:   app/functions/fn.cart.php
Line:   1905
Function:   {closure}
File:   /var/www/git/rees46_cscart_embedded/app/addons/rees46/controllers/backend/rees46.php
Line:   19
Function:   fn_get_order_info
File:   app/functions/fn.control.php
Line:   680
Function:   include
File:   app/functions/fn.control.php
Line:   451
Function:   fn_run_controller
File:   admin.php
Line:   28
Function:   fn_dispatch

**Comment by noff** [comment]
Это проблема в коде/демоданных CS-Cart

При работе с демонстрационными данными, созданными при установке движка, этот код выдает Notice:

```
        ini_set('display_errors', 'on');
        fn_get_order_info("51");
        die();
```
